src/Entity/Message.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MessageRepository")
 */
class Message
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $subject;

    /**
     * @ORM\Column(type="text")
     */
    private $body;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_archived;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     */
    private $from_user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     */
    private $to_user;


    public function getId()
    {
        return $this->id;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(string $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function toJson()
    {
        return [
            'from_user' => $this->from_user->toJson(),
            'to_user' => $this->to_user->toJson(),
            'subject' => $this->subject,
            'body' => $this->body
        ];
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsArchived(): ?bool
    {
        return $this->is_archived;
    }

    public function setIsArchived(?bool $is_archived): self
    {
        $this->is_archived = $is_archived;

        return $this;
    }

    public function getFromUser(): ?User
    {
        return $this->from_user;
    }

    public function setFromUser(?User $from_user): self
    {
        $this->from_user = $from_user;

        return $this;
    }

    public function getToUser(): ?User
    {
        return $this->to_user;
    }

    public function setToUser(?User $to_user): self
    {
        $this->to_user = $to_user;

        return $this;
    }

}

src/Form/MessageType.php
<?php

namespace App\Form;

use App\Entity\Message;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MessageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('subject')
            ->add('body')
            ->add('created_at')
            ->add('is_archived')
            ->add('from_user')
            ->add('to_user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Message::class,
        ]);
    }
}

src/Controller/MessageController.php
<?php

namespace App\Controller;

use App\Entity\Message;
use App\Form\Message1Type;
use App\Repository\MessageRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * @Route("/message")
 */
class MessageController extends Controller
{
    /**
     * @Route("/", name="message_index", methods="GET")
     */
    public function index(MessageRepository $messageRepository): Response
    {
        return $this->render('message/index.html.twig', ['messages' => $messageRepository->findAll()]);
    }

    /**
     * @Route("/new", name="message_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $message = new Message();
        $form = $this->createForm(Message1Type::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($message);
            $em->flush();

            return $this->redirectToRoute('message_index');
        }

        return $this->render('message/new.html.twig', [
            'message' => $message,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/new/api", name="message_new_api", methods="GET|POST")
     */
    public function new_api(Request $request, UserRepository $userRepository)
    {
        $data  = json_decode($request->getContent(), true);
        $now = new \DateTime();

        $from_user = $userRepository->find($data['from_user']);
        $to_user = $userRepository->find($data['to_user']);

        $message = new Message();
        $message->setSubject($data['subject']);
        $message->setBody($data['body']);
        $message->setFromUser($from_user);
        $message->setToUser($to_user);
        $message->setCreatedAt(new \DateTime());

        $em = $this->getDoctrine()->getManager();
        $em->persist($message);
        $em->flush();

        return new JsonResponse($data);
    }

    /**
     * @Route("/get_received/{user_id}", name="get_messages_received", methods="GET")
     */
    public function get_received_for_user(MessageRepository $jobRepository, $user_id)
    {
//        $user_jobs = $jobRepository->findBy(['user' => $user_id]);
        $repository = $this->getDoctrine()->getRepository('App\Entity\Message');

        $query = $repository->createQueryBuilder('a')
            ->join('a.to_user', 'd')
            ->where('d.id= :id')
            ->andWhere('a.is_archived is null')
            ->setParameter('id', $user_id)
            ->orderBy('a.created_at', 'DESC')
            ->getQuery();

        $messages = $query->getResult();

        $messages_to_send = [];

        foreach($messages as $job){
            $messages_to_send[] = $job->toJson();
        }

        return new JsonResponse($messages_to_send);
    }

    /**
     * @Route("/get_sent/{user_id}", name="get_messages_sent", methods="GET")
     */
    public function get_sent_for_user($user_id): Response
    {
        $repository = $this->getDoctrine()->getRepository('App\Entity\Message');

        $query = $repository->createQueryBuilder('a')
            ->join('a.from_user', 'd')
            ->where('d.id= :id')
            ->andWhere('a.is_archived is null')
            ->setParameter('id', $user_id)
            ->orderBy('a.created_at', 'DESC')
            ->getQuery();

        $messages = $query->getResult();

        $messages_to_send = [];

        foreach($messages as $job){
            $messages_to_send[] = $job->toJson();
        }

        return new JsonResponse($messages_to_send);
    }

    /**
     * @Route("/get_archived/{user_id}", name="get_messages_archived", methods="GET")
     */
    public function get_archived_for_user($user_id): Response
    {
        $repository = $this->getDoctrine()->getRepository('App\Entity\Message');

        $query = $repository->createQueryBuilder('a')
            ->join('a.to_user', 'd')
            ->where('d.id= :id')
            ->andWhere('a.is_archived = 1')
            ->setParameter('id', $user_id)
            ->orderBy('a.created_at', 'DESC')
            ->getQuery();

        $messages = $query->getResult();

        $messages_to_send = [];

        foreach($messages as $job){
            $messages_to_send[] = $job->toJson();
        }

        return new JsonResponse($messages_to_send);
    }

    /**
     * @Route("/{id}", name="message_show", methods="GET")
     */
    public function show(Message $message): Response
    {
        return $this->render('message/show.html.twig', ['message' => $message]);
    }

    /**
     * @Route("/{id}/edit", name="message_edit", methods="GET|POST")
     */
    public function edit(Request $request, Message $message): Response
    {
        $form = $this->createForm(Message1Type::class, $message);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('message_edit', ['id' => $message->getId()]);
        }

        return $this->render('message/edit.html.twig', [
            'message' => $message,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="message_delete", methods="DELETE")
     */
    public function delete(Request $request, Message $message): Response
    {
        if ($this->isCsrfTokenValid('delete'.$message->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($message);
            $em->flush();
        }

        return $this->redirectToRoute('message_index');
    }
}

templates/message/_delete_form.html.twig
<form method="post" action="{{ path('message_delete', {'id': message.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ message.id) }}">
    <button class="btn">Delete</button>
</form>

templates/message/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/message/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Message{% endblock %}

{% block body %}
    <h1>Edit Message</h1>

    {{ include('message/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('message_index') }}">back to list</a>

    {{ include('message/_delete_form.html.twig') }}
{% endblock %}

templates/message/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Message index{% endblock %}

{% block body %}
    <h1>Message index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Subject</th>
                <th>Body</th>
                <th>Created_at</th>
                <th>Is_archived</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for message in messages %}
            <tr>
                <td>{{ message.id }}</td>
                <td>{{ message.subject }}</td>
                <td>{{ message.body }}</td>
                <td>{{ message.createdAt ? message.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ message.isArchived ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('message_show', {'id': message.id}) }}">show</a>
                    <a href="{{ path('message_edit', {'id': message.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('message_new') }}">Create new</a>
{% endblock %}

templates/message/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Message{% endblock %}

{% block body %}
    <h1>Create new Message</h1>

    {{ include('message/_form.html.twig') }}

    <a href="{{ path('message_index') }}">back to list</a>
{% endblock %}

templates/message/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Message{% endblock %}

{% block body %}
    <h1>Message</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ message.id }}</td>
            </tr>
            <tr>
                <th>Subject</th>
                <td>{{ message.subject }}</td>
            </tr>
            <tr>
                <th>Body</th>
                <td>{{ message.body }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ message.createdAt ? message.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Is_archived</th>
                <td>{{ message.isArchived ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('message_index') }}">back to list</a>

    <a href="{{ path('message_edit', {'id': message.id}) }}">edit</a>

    {{ include('message/_delete_form.html.twig') }}
{% endblock %}